src/structure/adjacencylist.rs, src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs, src/structure/pfc.rs, src/structure/vbyte.rs
"trait objects without an explicit `dyn` are deprecated" so added where warnings appeared when checking
=> adding 'dyn' where appropriate to resolve deprecated

src/layer/base.rs, src/layer/child.rs, src/layer/layer.rs, src/store/mod.rs, src/store/sync.rs
Calculate the node_and_value count in a more imperative way for better performance and a smaller stack.
=> Layer: calculate node_and_value_count non-recursive

src/layer/builder.rs
Iterate once to get all counts, instead of traversing two times
for both the node_and_value count and predicate_count.
=> builder.rs: optimize count by traversing only once

src/layer/base.rs, src/layer/child.rs, src/layer/layer.rs, src/store/mod.rs, src/store/sync.rs
Lookups have been refactored.
For each lookup type (SubjectLookup, SubjectPredicateLookup, PredicateLookup, ObjectLookup) there is now a 'Layer' version (LayerSubjectLookup, LayerSubjectPredciateLookup, LayerPredicateLookup, LayerObjectLookup) which represents a lookup in either the layer's additions or the layer's removals, without taking parent layers into account.
The original implementations for SubjectLookup, SubjectPredicateLookup, PredicateLookup and ObjectLookup have been removed, and have been replaced by single implementations, GenericSubjectLookup, GenericSubjectPredicateLookup, GenericPredicateLookup and GenericObjectLookup. These are implemented in terms of the new Layer Lookup traits.
Unlike the old Lookups these are not implemented recursively, so stack exhaustion should no …
=> Lookup refactor

src/layer/base.rs, src/layer/child.rs, src/layer/layer.rs, src/store/mod.rs, src/store/sync.rs, src/structure/pfc.rs
This changes `PfcBlock::get` and `PfcList::get` to return `Option<String>` to avoid using `panic` for out-of-range index arguments.
The low-level change trickles up through `layer::base` and `layer::child`, but the logic there is also simplified by removing a duplicate range check.
Fixes #28
=> pfc: Replace panic with Option

src/structure/pfc.rs, src/structure/vbyte.rs
* Remove unnecessary `VByte` struct
* Add error checking to decode
* Optimize encode loop
* Add slice wrapper for encoding that does error checking
* Add `Vec` wrapper for encoding that ensures the right size buffer
* Fix `encoding_len` for 0
* Lots of documentation
* Lots of tests
=> Rewrite vbyte.rs

src/structure/adjacencylist.rs, src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs, src/structure/pfc.rs, src/structure/wavelettree.rs
This change removes `Clone` from `struct`s and `impl`s in `src/structure/*.rs`.
This is actually the thing that started me down #31. It's is a much milder version, but I think it's necessary.
First, I'm not trying to rehash the same issue in #31. It's related, but I think this change is more important and easier to defend.
Second, please see [“Data structures do not duplicate derived trait bounds”](https://rust-lang.github.io/api-guidelines/future-proofing.html#data-structures-do-not-duplicate-derived-trait-bounds-c-struct-bounds) from the Rust API Guidelines for why “generic data structures should not use trait bounds that can be derived or do not otherwise add semantic value.” This applies directly to `Clone`, which (unlike `AsRef<[u8]>`) is not intrinsic to the `struct`s or the to …
=> Minimize the Clone trait bound in src/structure/*

src/structure/logarray.rs
The log array expects a 32-bit or greater architecture. This is just a compiler check to confirm that.
Related to #42.
=> Static assertion for the architecture bus width

src/structure/bitarray.rs, src/structure/bititer.rs, src/structure/mod.rs
This is a simple change that avoids creating a `Vec<bool>` of capacity 64 when iterating over the bits of a `u64`.
=> Use a more efficient bit iterator

src/structure/bitarray.rs, src/structure/logarray.rs, src/structure/pfc.rs, src/structure/util.rs
* Use `u64::to_be_bytes` instead of `BigEndian::write_u64`: avoids
unnecessary `Vec` creation.
* Prepend `util::` to make it easier to find the source of those
functions and to distinguish them from similar found in `tokio:io`.
=> src/structure/util.rs: minor cleanups

src/structure/adjacencylist.rs, src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs, src/structure/wavelettree.rs
Improvements to bitarray.rs (and logarray.rs)
* Add comments
* Add tests
* Add error handling
* Change `BitArrayFileBuilder` to operate on 8 bytes at a time instead of 1
* Replace `Box<dyn Future<...>>` with `impl Future<...>`
* Handle max values and overflow
* Use safer numeric casting (not `as`) to avoid unknown conversions
* Use clippy and apply some recommendations (e.g. `is_empty()`)
* Remove `'static` and `Send` where not needed
* Unify logarray.rs with the changes in bitarray.rs
=> Improvements to bitarray.rs (and logarray.rs)

CONTRIBUTING.md
Small text changes to remove references to GPL and replace with Apache 2.0
=> Remove References to GPL

Cargo.toml, src/storage/cache.rs, src/storage/directory.rs, src/storage/layer.rs, src/storage/memory.rs, src/storage/mod.rs, src/storage/pack.rs, src/store/mod.rs, src/store/sync.rs
This implements layer export and import for the PersistentLayerStore, which currently backs both the memory and the directory layer store (yes it is a bit of a misnomer).
This closes #58. It is also an initial step towards #62, implementing the pack functionality as a separate trait in its own file instead of as part of a bigger trait. It also makes use of the `async_trait` macro as mentioned in #56.
=> Implement layer export and import more generically

src/storage/directory.rs, src/storage/locking.rs, src/store/mod.rs, src/store/sync.rs
New methods in the store api which provide a way to retrieve the head graph layer and its version, and replace the current graph head as long as given version matches.
Closes #65.
=> Label versioned update

src/storage/directory.rs, src/storage/label.rs, src/storage/memory.rs, src/store/mod.rs, src/store/sync.rs
Code for deleting labels.
Closes #8, and contributes to #56.
=> Label deletion

src/layer/builder.rs, src/layer/internal/base.rs, src/layer/internal/child.rs, src/layer/internal/mod.rs, src/layer/internal/object_iterator.rs, src/layer/internal/predicate_iterator.rs, src/layer/internal/subject_iterator.rs, src/layer/simple_builder.rs, src/storage/delta.rs, src/storage/directory.rs, src/storage/file.rs, src/storage/layer.rs, src/storage/memory.rs, src/storage/pack.rs, src/structure/adjacencylist.rs, src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs, src/structure/pfc.rs, src/structure/wavelettree.rs
FileLoad and FileStore had various methods that did not return a future. They do now.
This closes #63 and contributes to #56.
=> fully futurize FileLoad and FileStore

src/layer/id_map.rs, src/store/mod.rs
Due to a coding error, when rolling up a stack of layers where one was previously rolled up, the node-value idmap was used instead of the predicate idmap, causing a lot of indexes to be wrongly mapped.
This pull request fixes that.
=> Fix rollup

src/store/mod.rs, src/store/sync.rs
It was previously not possible to compare two layers. Now it is.
=> Implement a way to compare layers which fails on delta rollups

src/structure/logarray.rs
LogArray::entry has been slightly improved.
In a logarray, an entry may be entirely within one aligned u64, or it may span two. In the existing code, we always retrieve two u64's, but will only use one if the entry doesn't span both. This patch will only retrieve that second u64 when it is actually needed.
It's a small change, and the speed improvement isn't huge, but LogArray::entry appears to be the most called function in TerminusDB by a large margin, so even small improvements matter a little.
=> Speed improvement in LogArray::entry for non-boundary cases

src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs
This pull request introduces some changes to the bitindex to make this faster.
1. when selecting from a range, only the blocks and superblocks in that range are considered.
2. Selecting from the full index is now implemented through range selection rather than the other way around.
3. When the range from which we're selecting is entirely in the same cache line, a linear scan is performed rather than a binary search.
4. Some asserts are now debug_asserts and therefore no longer happen in production code.
=> Optimizations to BitIndex

src/layer/internal/mod.rs, src/layer/internal/object_iterator.rs, src/layer/internal/predicate_iterator.rs, src/layer/internal/subject_iterator.rs
Various places in the code were allocating vectors that'd have to be grown at a later point, which could incur a full move of the existing array data to a new location in memory, incurring quite some overhead. This is now avoided by ensuring vectors are pre-allocated with the right size.
=> Pre-allocate vectors instead of growing them dynamically

.github/workflows/other_platforms.yml, .github/workflows/test.yml
This enables ARM64 testing in CI. All the tests pass.
Unfortunately I have to run it in QEMU since Github has no available ARM64 machines. It therefore runs very slowly, it takes almost 35 minutes to compile. Hence why I added a nightly cron instead of running it on every push and PR.
Also, please squash this PR since it contains a lot of experiments and I don't want to pollute the commit history.
=> Enable arm64 testing in CI

src/storage/directory.rs
Label list retrieval did not actually work for the directory store. This fixes that.
=> fix label list retrieval for the directory store

src/structure/pfc.rs
The existing pfc dict streaming logic was wrong, as it did not properly detect the end of a pfc dict file, and instead terminated early for some edge cases. It was also slightly wrong in how it handled incomplete intermediate reads. We ran into this while trying to convert a large layer and finding out it was missing half its dictionary.
This pull changes the way pfc dicts are iterated from disk. It now takes into account the full length of the dictionary and will keep going until that many elements have been returned. This also changes the interface slightly, as we need to know the total size of a dictionary up front to do this iteration, so we can't just consume an arbitrary reader. For convenience, extra functions have been added which operate on a dictionary file rather than an …
=> fix pfc dict streaming

src/storage/pack.rs
on unpack, we were not finalizing layers. This is required however for the archive store to work properly, as otherwise layers are never moved from memory into persistent storage.
This pull adds a finalization step to unpack.
=> Call finalize on layers after unpacking them

Cargo.toml, src/storage/archive.rs, src/storage/layer.rs, src/store/mod.rs, src/structure/tfc/block.rs
In the squash refactor I forgot to make sure unused dict entries are deleted. This PR does a use check for all squashed dict entries and removes the ones that are unused.
=> delete unused dict entries in a squash

benches/builder/main.rs, src/layer/simple_builder.rs
This PR changes the simple builder to deduplicate strings. This ensures a much smaller memory footprint. It's also faster, despite not being multi-threaded anymore.
I might reintroduce multi-threading in some parts though.
=> use less memory in builders

Cargo.toml
Releasing now to prepare the release of TerminusDB with the memory use optimizations.
=> Raise version to 0.21.0

src/structure/tfc/decimal.rs, src/structure/tfc/typed.rs
Currently we do not support normal XSD decimal notation which can use scientific notation. I've extended the parser to do this correctly.
=> Add scientific notation to terminus store

src/layer/internal/base.rs, src/layer/internal/child.rs, src/layer/internal/mod.rs, src/layer/internal/object_iterator.rs, src/layer/internal/predicate_iterator.rs, src/layer/internal/subject_iterator.rs, src/layer/layer.rs, src/structure/adjacencylist.rs, src/structure/bitarray.rs, src/structure/bitindex.rs, src/structure/logarray.rs
We still had some data structures that required the file abstraction to be built. With these changes, each of our internal structures is buildable without files.
=> More buf builders

src/structure/tfc/datetime.rs
Please read
<https://github.com/terminusdb/terminusdb-store/blob/main/CONTRIBUTING.md>
before submitting a pull request.
=> Fix for bug in before epoch dates

benches/bench.rs, benches/builder/main.rs, src/layer/builder.rs, src/layer/internal/mod.rs, src/layer/simple_builder.rs, src/storage/delta.rs, src/storage/directory.rs, src/storage/layer.rs
`id_object_is_node` had an edge case where it'd return None for cases where it should have returned a Some, causing processes that depended on the direct behavior to panic.
This replaces the implementation with a replica of `id_object` minus the dictionary lookup. Assuming `id_object` is correct, `id_object_is_node` (and by extension `id_object_is_value`) will now also be correct.
=> Fix id_object_is_node
